version: '3.4'

services:
  web_api:
    image: web_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Kuala_Lumpur"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"

