version: '3.4'

services:
  web_api:
    image: web_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Kuala_Lumpur"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:5000"
